// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: CanDisplay83

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Group_Boost;
lv_obj_t * ui_BoostLabel;
lv_obj_t * ui_BoostBar;
lv_obj_t * ui_BoostValue;
lv_obj_t * ui_Group_Map;
lv_obj_t * ui_MapLabel;
lv_obj_t * ui_MapValue;
lv_obj_t * ui_MapTypeLabel;
lv_obj_t * ui_Group_RPM;
lv_obj_t * ui_RPMLabel;
lv_obj_t * ui_RPMValue;
lv_obj_t * ui_RpmBar;
lv_obj_t * ui_RPMTypeLabel;
lv_obj_t * ui_Group_AFR;
lv_obj_t * ui_AFRLabel;
lv_obj_t * ui_AFRValue;
lv_obj_t * ui_AFRTypeLabel;
lv_obj_t * ui_Group_IAT;
lv_obj_t * ui_IATLabel;
lv_obj_t * ui_IATValue;
lv_obj_t * ui_IATTypeLabel;
lv_obj_t * ui_Group_Coolant;
lv_obj_t * ui_CoolantLabel;
lv_obj_t * ui_CoolantValue;
lv_obj_t * ui_CoolantTypeLabel;
lv_obj_t * ui_Group_Speed;
lv_obj_t * ui_SpeedLabel;
lv_obj_t * ui_SpeedValue;
lv_obj_t * ui_SpeedTypeLabel;
lv_obj_t * ui_Group_Knock;
lv_obj_t * ui_KnockLabel;
lv_obj_t * ui_KnockValue;
lv_obj_t * ui_KnockTypeLabel;
lv_obj_t * ui_Group_Fuel_Pressure;
lv_obj_t * ui_FuelPressureLabel;
lv_obj_t * ui_FuelPressureValue;
lv_obj_t * ui_FuelPressureTypeLabel;
lv_obj_t * ui_Group_Fuel_Battery;
lv_obj_t * ui_BatteryvoltageLabel;
lv_obj_t * ui_BatteryvoltageValue;
lv_obj_t * ui_BatteryvoltageTypeLabel;
lv_obj_t * ui_Group_Fuel_ignition;
lv_obj_t * ui_IgnitionLabel;
lv_obj_t * ui_IgnitionValue;
lv_obj_t * ui_IgnitionTypeLabel;
lv_obj_t * ui_Group_Fuel_duty;
lv_obj_t * ui_FueldutyLabel;
lv_obj_t * ui_FueldutyValue;
lv_obj_t * ui_FueldutyTypeLabel;
lv_obj_t * ui_Group_Rotrex;
lv_obj_t * ui_RotrexLabel;
lv_obj_t * ui_RatioValue;
lv_obj_t * ui_TurboSpeedValue;
lv_obj_t * ui_RatioTypeLabel;
lv_obj_t * ui_TurboSpeedTypeLabel;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
