// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: CanDisplay83

#ifndef _CANDISPLAY83_UI_H
#define _CANDISPLAY83_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Group_Boost;
extern lv_obj_t * ui_BoostLabel;
extern lv_obj_t * ui_BoostBar;
extern lv_obj_t * ui_BoostValue;
extern lv_obj_t * ui_Group_Map;
extern lv_obj_t * ui_MapLabel;
extern lv_obj_t * ui_MapValue;
extern lv_obj_t * ui_MapTypeLabel;
extern lv_obj_t * ui_Group_RPM;
extern lv_obj_t * ui_RPMLabel;
extern lv_obj_t * ui_RPMValue;
extern lv_obj_t * ui_RpmBar;
extern lv_obj_t * ui_RPMTypeLabel;
extern lv_obj_t * ui_Group_AFR;
extern lv_obj_t * ui_AFRLabel;
extern lv_obj_t * ui_AFRValue;
extern lv_obj_t * ui_AFRTypeLabel;
extern lv_obj_t * ui_Group_IAT;
extern lv_obj_t * ui_IATLabel;
extern lv_obj_t * ui_IATValue;
extern lv_obj_t * ui_IATTypeLabel;
extern lv_obj_t * ui_Group_Coolant;
extern lv_obj_t * ui_CoolantLabel;
extern lv_obj_t * ui_CoolantValue;
extern lv_obj_t * ui_CoolantTypeLabel;
extern lv_obj_t * ui_Group_Speed;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_SpeedTypeLabel;
extern lv_obj_t * ui_Group_Knock;
extern lv_obj_t * ui_KnockLabel;
extern lv_obj_t * ui_KnockValue;
extern lv_obj_t * ui_KnockTypeLabel;
extern lv_obj_t * ui_Group_Fuel_Pressure;
extern lv_obj_t * ui_FuelPressureLabel;
extern lv_obj_t * ui_FuelPressureValue;
extern lv_obj_t * ui_FuelPressureTypeLabel;
extern lv_obj_t * ui_Group_Fuel_Battery;
extern lv_obj_t * ui_BatteryvoltageLabel;
extern lv_obj_t * ui_BatteryvoltageValue;
extern lv_obj_t * ui_BatteryvoltageTypeLabel;
extern lv_obj_t * ui_Group_Fuel_ignition;
extern lv_obj_t * ui_IgnitionLabel;
extern lv_obj_t * ui_IgnitionValue;
extern lv_obj_t * ui_IgnitionTypeLabel;
extern lv_obj_t * ui_Group_Fuel_duty;
extern lv_obj_t * ui_FueldutyLabel;
extern lv_obj_t * ui_FueldutyValue;
extern lv_obj_t * ui_FueldutyTypeLabel;
extern lv_obj_t * ui_Group_Rotrex;
extern lv_obj_t * ui_RotrexLabel;
extern lv_obj_t * ui_RatioValue;
extern lv_obj_t * ui_TurboSpeedValue;
extern lv_obj_t * ui_RatioTypeLabel;
extern lv_obj_t * ui_TurboSpeedTypeLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_90676448);    // assets/pngegg (2).png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
