// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: CanDisplay83

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x090808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_90676448);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -314);
    lv_obj_set_y(ui_Image1, -152);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 160);

    ui_Group_Boost = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Boost, 480);
    lv_obj_set_height(ui_Group_Boost, 60);
    lv_obj_set_x(ui_Group_Boost, -150);
    lv_obj_set_y(ui_Group_Boost, 18);
    lv_obj_set_align(ui_Group_Boost, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Boost, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Boost, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Boost, lv_color_hex(0x080808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Boost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Boost, lv_color_hex(0xF50404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Boost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BoostLabel = lv_label_create(ui_Group_Boost);
    lv_obj_set_width(ui_BoostLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BoostLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BoostLabel, -217);
    lv_obj_set_y(ui_BoostLabel, -14);
    lv_obj_set_align(ui_BoostLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BoostLabel, "PSI");
    lv_obj_set_style_text_color(ui_BoostLabel, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BoostLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BoostLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BoostBar = lv_bar_create(ui_Group_Boost);
    lv_bar_set_range(ui_BoostBar, 0, 12);
    lv_obj_set_width(ui_BoostBar, 280);
    lv_obj_set_height(ui_BoostBar, 26);
    lv_obj_set_x(ui_BoostBar, -45);
    lv_obj_set_y(ui_BoostBar, -1);
    lv_obj_set_align(ui_BoostBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BoostBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BoostBar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BoostBar, lv_color_hex(0x23EE14), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BoostBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BoostBar, lv_color_hex(0xF61C0A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BoostBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BoostBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BoostBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BoostValue = lv_label_create(ui_Group_Boost);
    lv_obj_set_width(ui_BoostValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BoostValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BoostValue, 156);
    lv_obj_set_y(ui_BoostValue, 0);
    lv_obj_set_align(ui_BoostValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BoostValue, "0");
    lv_obj_set_style_text_color(ui_BoostValue, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BoostValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_BoostValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_BoostValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BoostValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Map = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Map, 134);
    lv_obj_set_height(ui_Group_Map, 160);
    lv_obj_set_x(ui_Group_Map, -495);
    lv_obj_set_y(ui_Group_Map, 296);
    lv_obj_set_align(ui_Group_Map, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Map, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Map, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Map, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Map, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Map, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Map, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapLabel = lv_label_create(ui_Group_Map);
    lv_obj_set_width(ui_MapLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MapLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MapLabel, -12);
    lv_obj_set_y(ui_MapLabel, -14);
    lv_label_set_text(ui_MapLabel, "Map");
    lv_obj_set_style_text_color(ui_MapLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MapLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MapLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapValue = lv_label_create(ui_Group_Map);
    lv_obj_set_width(ui_MapValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MapValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MapValue, 2);
    lv_obj_set_y(ui_MapValue, -1);
    lv_obj_set_align(ui_MapValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MapValue, "0");
    lv_obj_set_style_text_color(ui_MapValue, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MapValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MapValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MapValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MapValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapTypeLabel = lv_label_create(ui_Group_Map);
    lv_obj_set_width(ui_MapTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MapTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MapTypeLabel, 8);
    lv_obj_set_y(ui_MapTypeLabel, 8);
    lv_obj_set_align(ui_MapTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_MapTypeLabel, "kPa");
    lv_obj_set_style_text_color(ui_MapTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MapTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MapTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_RPM = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_RPM, 480);
    lv_obj_set_height(ui_Group_RPM, 60);
    lv_obj_set_x(ui_Group_RPM, -310);
    lv_obj_set_y(ui_Group_RPM, 161);
    lv_obj_set_align(ui_Group_RPM, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_RPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_RPM, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_RPM, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_RPM, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMLabel = lv_label_create(ui_Group_RPM);
    lv_obj_set_width(ui_RPMLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMLabel, -12);
    lv_obj_set_y(ui_RPMLabel, -14);
    lv_label_set_text(ui_RPMLabel, "RPM");
    lv_obj_set_style_text_color(ui_RPMLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMValue = lv_label_create(ui_Group_RPM);
    lv_obj_set_width(ui_RPMValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMValue, 156);
    lv_obj_set_y(ui_RPMValue, 0);
    lv_obj_set_align(ui_RPMValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMValue, "0");
    lv_obj_set_style_text_color(ui_RPMValue, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_RPMValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_RPMValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RpmBar = lv_bar_create(ui_Group_RPM);
    lv_bar_set_range(ui_RpmBar, 0, 6500);
    lv_obj_set_width(ui_RpmBar, 280);
    lv_obj_set_height(ui_RpmBar, 26);
    lv_obj_set_x(ui_RpmBar, -45);
    lv_obj_set_y(ui_RpmBar, -1);
    lv_obj_set_align(ui_RpmBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RpmBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RpmBar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RpmBar, lv_color_hex(0x23EE14), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RpmBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RpmBar, lv_color_hex(0xF61C0A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RpmBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RpmBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RpmBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RPMTypeLabel = lv_label_create(ui_Group_RPM);
    lv_obj_set_width(ui_RPMTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMTypeLabel, 8);
    lv_obj_set_y(ui_RPMTypeLabel, 8);
    lv_obj_set_align(ui_RPMTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_RPMTypeLabel, "");
    lv_obj_set_style_text_color(ui_RPMTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMTypeLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_AFR = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_AFR, 134);
    lv_obj_set_height(ui_Group_AFR, 160);
    lv_obj_set_x(ui_Group_AFR, -335);
    lv_obj_set_y(ui_Group_AFR, 296);
    lv_obj_set_align(ui_Group_AFR, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_AFR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_AFR, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_AFR, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_AFR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_AFR, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_AFR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AFRLabel = lv_label_create(ui_Group_AFR);
    lv_obj_set_width(ui_AFRLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AFRLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AFRLabel, -12);
    lv_obj_set_y(ui_AFRLabel, -14);
    lv_label_set_text(ui_AFRLabel, "Lambda");
    lv_obj_set_style_text_color(ui_AFRLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AFRLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AFRLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AFRValue = lv_label_create(ui_Group_AFR);
    lv_obj_set_width(ui_AFRValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AFRValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AFRValue, 2);
    lv_obj_set_y(ui_AFRValue, -1);
    lv_obj_set_align(ui_AFRValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AFRValue, "0");
    lv_obj_set_style_text_color(ui_AFRValue, lv_color_hex(0x06F70D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AFRValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_AFRValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_AFRValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AFRValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AFRTypeLabel = lv_label_create(ui_Group_AFR);
    lv_obj_set_width(ui_AFRTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AFRTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AFRTypeLabel, 8);
    lv_obj_set_y(ui_AFRTypeLabel, 8);
    lv_obj_set_align(ui_AFRTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_AFRTypeLabel, "");
    lv_obj_set_style_text_color(ui_AFRTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AFRTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AFRTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_IAT = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_IAT, 134);
    lv_obj_set_height(ui_Group_IAT, 133);
    lv_obj_set_x(ui_Group_IAT, -175);
    lv_obj_set_y(ui_Group_IAT, 24);
    lv_obj_set_align(ui_Group_IAT, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_IAT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_IAT, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_IAT, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_IAT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_IAT, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_IAT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IATLabel = lv_label_create(ui_Group_IAT);
    lv_obj_set_width(ui_IATLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IATLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IATLabel, -12);
    lv_obj_set_y(ui_IATLabel, -14);
    lv_label_set_text(ui_IATLabel, "IAT");
    lv_obj_set_style_text_color(ui_IATLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IATLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IATLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IATValue = lv_label_create(ui_Group_IAT);
    lv_obj_set_width(ui_IATValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IATValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IATValue, 2);
    lv_obj_set_y(ui_IATValue, -1);
    lv_obj_set_align(ui_IATValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IATValue, "0");
    lv_obj_set_style_text_color(ui_IATValue, lv_color_hex(0x06F70D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IATValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IATValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IATValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IATValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IATTypeLabel = lv_label_create(ui_Group_IAT);
    lv_obj_set_width(ui_IATTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IATTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IATTypeLabel, 8);
    lv_obj_set_y(ui_IATTypeLabel, 8);
    lv_obj_set_align(ui_IATTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_IATTypeLabel, "°C");
    lv_obj_set_style_text_color(ui_IATTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IATTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IATTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Coolant = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Coolant, 134);
    lv_obj_set_height(ui_Group_Coolant, 133);
    lv_obj_set_x(ui_Group_Coolant, -15);
    lv_obj_set_y(ui_Group_Coolant, 24);
    lv_obj_set_align(ui_Group_Coolant, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Coolant, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Coolant, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Coolant, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Coolant, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Coolant, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Coolant, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoolantLabel = lv_label_create(ui_Group_Coolant);
    lv_obj_set_width(ui_CoolantLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoolantLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoolantLabel, -12);
    lv_obj_set_y(ui_CoolantLabel, -14);
    lv_label_set_text(ui_CoolantLabel, "CLT");
    lv_obj_set_style_text_color(ui_CoolantLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CoolantLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CoolantLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoolantValue = lv_label_create(ui_Group_Coolant);
    lv_obj_set_width(ui_CoolantValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoolantValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoolantValue, 2);
    lv_obj_set_y(ui_CoolantValue, -1);
    lv_obj_set_align(ui_CoolantValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CoolantValue, "0");
    lv_obj_set_style_text_color(ui_CoolantValue, lv_color_hex(0x06F70D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CoolantValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_CoolantValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_CoolantValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CoolantValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoolantTypeLabel = lv_label_create(ui_Group_Coolant);
    lv_obj_set_width(ui_CoolantTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoolantTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoolantTypeLabel, 8);
    lv_obj_set_y(ui_CoolantTypeLabel, 8);
    lv_obj_set_align(ui_CoolantTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_CoolantTypeLabel, "°C");
    lv_obj_set_style_text_color(ui_CoolantTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CoolantTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CoolantTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Speed = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Speed, 134);
    lv_obj_set_height(ui_Group_Speed, 133);
    lv_obj_set_x(ui_Group_Speed, -495);
    lv_obj_set_y(ui_Group_Speed, 24);
    lv_obj_set_align(ui_Group_Speed, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Speed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Speed, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Speed, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Speed, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLabel = lv_label_create(ui_Group_Speed);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel, -12);
    lv_obj_set_y(ui_SpeedLabel, -14);
    lv_label_set_text(ui_SpeedLabel, "GPS Speed");
    lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValue = lv_label_create(ui_Group_Speed);
    lv_obj_set_width(ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedValue, 2);
    lv_obj_set_y(ui_SpeedValue, -1);
    lv_obj_set_align(ui_SpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue, "0");
    lv_obj_set_style_text_color(ui_SpeedValue, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SpeedValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SpeedValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedTypeLabel = lv_label_create(ui_Group_Speed);
    lv_obj_set_width(ui_SpeedTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedTypeLabel, 8);
    lv_obj_set_y(ui_SpeedTypeLabel, 8);
    lv_obj_set_align(ui_SpeedTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_SpeedTypeLabel, "km/h");
    lv_obj_set_style_text_color(ui_SpeedTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Knock = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Knock, 134);
    lv_obj_set_height(ui_Group_Knock, 133);
    lv_obj_set_x(ui_Group_Knock, -335);
    lv_obj_set_y(ui_Group_Knock, 24);
    lv_obj_set_align(ui_Group_Knock, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Knock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Knock, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Knock, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Knock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Knock, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Knock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KnockLabel = lv_label_create(ui_Group_Knock);
    lv_obj_set_width(ui_KnockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KnockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KnockLabel, -12);
    lv_obj_set_y(ui_KnockLabel, -14);
    lv_label_set_text(ui_KnockLabel, "Knock");
    lv_obj_set_style_text_color(ui_KnockLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KnockLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_KnockLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KnockValue = lv_label_create(ui_Group_Knock);
    lv_obj_set_width(ui_KnockValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KnockValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KnockValue, 2);
    lv_obj_set_y(ui_KnockValue, -1);
    lv_obj_set_align(ui_KnockValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KnockValue, "0");
    lv_obj_set_style_text_color(ui_KnockValue, lv_color_hex(0xFB0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KnockValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_KnockValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_KnockValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_KnockValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KnockTypeLabel = lv_label_create(ui_Group_Knock);
    lv_obj_set_width(ui_KnockTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KnockTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KnockTypeLabel, 8);
    lv_obj_set_y(ui_KnockTypeLabel, 8);
    lv_obj_set_align(ui_KnockTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_KnockTypeLabel, "count");
    lv_obj_set_style_text_color(ui_KnockTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KnockTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_KnockTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Fuel_Pressure = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Fuel_Pressure, 134);
    lv_obj_set_height(ui_Group_Fuel_Pressure, 133);
    lv_obj_set_x(ui_Group_Fuel_Pressure, -175);
    lv_obj_set_y(ui_Group_Fuel_Pressure, 174);
    lv_obj_set_align(ui_Group_Fuel_Pressure, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Fuel_Pressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Fuel_Pressure, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Fuel_Pressure, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Fuel_Pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Fuel_Pressure, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Fuel_Pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FuelPressureLabel = lv_label_create(ui_Group_Fuel_Pressure);
    lv_obj_set_width(ui_FuelPressureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FuelPressureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuelPressureLabel, -12);
    lv_obj_set_y(ui_FuelPressureLabel, -14);
    lv_label_set_text(ui_FuelPressureLabel, "Fuel Pressure");
    lv_obj_set_style_text_color(ui_FuelPressureLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FuelPressureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FuelPressureLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FuelPressureValue = lv_label_create(ui_Group_Fuel_Pressure);
    lv_obj_set_width(ui_FuelPressureValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FuelPressureValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuelPressureValue, 2);
    lv_obj_set_y(ui_FuelPressureValue, -1);
    lv_obj_set_align(ui_FuelPressureValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FuelPressureValue, "0");
    lv_obj_set_style_text_color(ui_FuelPressureValue, lv_color_hex(0x06F70D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FuelPressureValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_FuelPressureValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FuelPressureValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FuelPressureValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FuelPressureTypeLabel = lv_label_create(ui_Group_Fuel_Pressure);
    lv_obj_set_width(ui_FuelPressureTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FuelPressureTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuelPressureTypeLabel, 8);
    lv_obj_set_y(ui_FuelPressureTypeLabel, 8);
    lv_obj_set_align(ui_FuelPressureTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_FuelPressureTypeLabel, "kPa");
    lv_obj_set_style_text_color(ui_FuelPressureTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FuelPressureTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FuelPressureTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Fuel_Battery = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Fuel_Battery, 134);
    lv_obj_set_height(ui_Group_Fuel_Battery, 133);
    lv_obj_set_x(ui_Group_Fuel_Battery, -15);
    lv_obj_set_y(ui_Group_Fuel_Battery, 174);
    lv_obj_set_align(ui_Group_Fuel_Battery, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Fuel_Battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Fuel_Battery, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Fuel_Battery, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Fuel_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Fuel_Battery, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Fuel_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryvoltageLabel = lv_label_create(ui_Group_Fuel_Battery);
    lv_obj_set_width(ui_BatteryvoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryvoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryvoltageLabel, -12);
    lv_obj_set_y(ui_BatteryvoltageLabel, -14);
    lv_label_set_text(ui_BatteryvoltageLabel, "Battery");
    lv_obj_set_style_text_color(ui_BatteryvoltageLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryvoltageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryvoltageLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryvoltageValue = lv_label_create(ui_Group_Fuel_Battery);
    lv_obj_set_width(ui_BatteryvoltageValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryvoltageValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryvoltageValue, 2);
    lv_obj_set_y(ui_BatteryvoltageValue, -1);
    lv_obj_set_align(ui_BatteryvoltageValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryvoltageValue, "0");
    lv_obj_set_style_text_color(ui_BatteryvoltageValue, lv_color_hex(0x06F70D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryvoltageValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_BatteryvoltageValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_BatteryvoltageValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryvoltageValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryvoltageTypeLabel = lv_label_create(ui_Group_Fuel_Battery);
    lv_obj_set_width(ui_BatteryvoltageTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryvoltageTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryvoltageTypeLabel, 8);
    lv_obj_set_y(ui_BatteryvoltageTypeLabel, 8);
    lv_obj_set_align(ui_BatteryvoltageTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_BatteryvoltageTypeLabel, "V");
    lv_obj_set_style_text_color(ui_BatteryvoltageTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryvoltageTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryvoltageTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Fuel_ignition = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Fuel_ignition, 134);
    lv_obj_set_height(ui_Group_Fuel_ignition, 133);
    lv_obj_set_x(ui_Group_Fuel_ignition, -15);
    lv_obj_set_y(ui_Group_Fuel_ignition, 323);
    lv_obj_set_align(ui_Group_Fuel_ignition, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Fuel_ignition, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Fuel_ignition, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Fuel_ignition, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Fuel_ignition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Fuel_ignition, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Fuel_ignition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IgnitionLabel = lv_label_create(ui_Group_Fuel_ignition);
    lv_obj_set_width(ui_IgnitionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IgnitionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IgnitionLabel, -12);
    lv_obj_set_y(ui_IgnitionLabel, -14);
    lv_label_set_text(ui_IgnitionLabel, "Ignition comp");
    lv_obj_set_style_text_color(ui_IgnitionLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IgnitionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IgnitionLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IgnitionValue = lv_label_create(ui_Group_Fuel_ignition);
    lv_obj_set_width(ui_IgnitionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IgnitionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IgnitionValue, 2);
    lv_obj_set_y(ui_IgnitionValue, -1);
    lv_obj_set_align(ui_IgnitionValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IgnitionValue, "0");
    lv_obj_set_style_text_color(ui_IgnitionValue, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IgnitionValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IgnitionValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IgnitionValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IgnitionValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IgnitionTypeLabel = lv_label_create(ui_Group_Fuel_ignition);
    lv_obj_set_width(ui_IgnitionTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IgnitionTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IgnitionTypeLabel, 8);
    lv_obj_set_y(ui_IgnitionTypeLabel, 8);
    lv_obj_set_align(ui_IgnitionTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_IgnitionTypeLabel, "deg");
    lv_obj_set_style_text_color(ui_IgnitionTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IgnitionTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IgnitionTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Fuel_duty = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Fuel_duty, 134);
    lv_obj_set_height(ui_Group_Fuel_duty, 133);
    lv_obj_set_x(ui_Group_Fuel_duty, -175);
    lv_obj_set_y(ui_Group_Fuel_duty, 323);
    lv_obj_set_align(ui_Group_Fuel_duty, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Group_Fuel_duty, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Fuel_duty, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Fuel_duty, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Fuel_duty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Fuel_duty, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Fuel_duty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FueldutyLabel = lv_label_create(ui_Group_Fuel_duty);
    lv_obj_set_width(ui_FueldutyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FueldutyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FueldutyLabel, -12);
    lv_obj_set_y(ui_FueldutyLabel, -14);
    lv_label_set_text(ui_FueldutyLabel, "Fuel duty");
    lv_obj_set_style_text_color(ui_FueldutyLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FueldutyLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FueldutyLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FueldutyValue = lv_label_create(ui_Group_Fuel_duty);
    lv_obj_set_width(ui_FueldutyValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FueldutyValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FueldutyValue, 2);
    lv_obj_set_y(ui_FueldutyValue, -1);
    lv_obj_set_align(ui_FueldutyValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FueldutyValue, "0");
    lv_obj_set_style_text_color(ui_FueldutyValue, lv_color_hex(0x06F70D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FueldutyValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_FueldutyValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FueldutyValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FueldutyValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FueldutyTypeLabel = lv_label_create(ui_Group_Fuel_duty);
    lv_obj_set_width(ui_FueldutyTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FueldutyTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FueldutyTypeLabel, 8);
    lv_obj_set_y(ui_FueldutyTypeLabel, 8);
    lv_obj_set_align(ui_FueldutyTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_FueldutyTypeLabel, "%");
    lv_obj_set_style_text_color(ui_FueldutyTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FueldutyTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FueldutyTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Rotrex = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Group_Rotrex, 134);
    lv_obj_set_height(ui_Group_Rotrex, 160);
    lv_obj_set_x(ui_Group_Rotrex, -323);
    lv_obj_set_y(ui_Group_Rotrex, 135);
    lv_obj_set_align(ui_Group_Rotrex, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Rotrex, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Rotrex, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Rotrex, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Rotrex, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Rotrex, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Rotrex, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RotrexLabel = lv_label_create(ui_Group_Rotrex);
    lv_obj_set_width(ui_RotrexLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RotrexLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RotrexLabel, -12);
    lv_obj_set_y(ui_RotrexLabel, -14);
    lv_label_set_text(ui_RotrexLabel, "Rotrex");
    lv_obj_set_style_text_color(ui_RotrexLabel, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RotrexLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RotrexLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RatioValue = lv_label_create(ui_Group_Rotrex);
    lv_obj_set_width(ui_RatioValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RatioValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RatioValue, 1);
    lv_obj_set_y(ui_RatioValue, -35);
    lv_obj_set_align(ui_RatioValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RatioValue, "0");
    lv_obj_set_style_text_color(ui_RatioValue, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RatioValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_RatioValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_RatioValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RatioValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TurboSpeedValue = lv_label_create(ui_Group_Rotrex);
    lv_obj_set_width(ui_TurboSpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TurboSpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TurboSpeedValue, 0);
    lv_obj_set_y(ui_TurboSpeedValue, 33);
    lv_obj_set_align(ui_TurboSpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TurboSpeedValue, "0");
    lv_obj_set_style_text_color(ui_TurboSpeedValue, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TurboSpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TurboSpeedValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TurboSpeedValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TurboSpeedValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RatioTypeLabel = lv_label_create(ui_Group_Rotrex);
    lv_obj_set_width(ui_RatioTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RatioTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RatioTypeLabel, 8);
    lv_obj_set_y(ui_RatioTypeLabel, -54);
    lv_obj_set_align(ui_RatioTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_RatioTypeLabel, "Ratio");
    lv_obj_set_style_text_color(ui_RatioTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RatioTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RatioTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TurboSpeedTypeLabel = lv_label_create(ui_Group_Rotrex);
    lv_obj_set_width(ui_TurboSpeedTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TurboSpeedTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TurboSpeedTypeLabel, 8);
    lv_obj_set_y(ui_TurboSpeedTypeLabel, 14);
    lv_obj_set_align(ui_TurboSpeedTypeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_TurboSpeedTypeLabel, "Rpm");
    lv_obj_set_style_text_color(ui_TurboSpeedTypeLabel, lv_color_hex(0x03FAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TurboSpeedTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TurboSpeedTypeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
